### ISSUE TITLE
BE: 자랑 게시판 API 관련 기능 구현

### ISSUE THREAD

**Issue by xjfcnfw3** [Side-Effect-Team/side-effect-backend#18]
# Description
인증 객체를 받아내는 API 기능 구현

# To-do
- [x] 게시판 추가 기능
- [x] 게시판 삭제 기능
- [x] 게시판 수정 기능

# ETC
