### ISSUE TITLE
BE: 모집 게시판 API 기능 구현 및 DTO 구조 수정

### ISSUE THREAD

**Issue by sksrpf1126** [Side-Effect-Team/side-effect-backend#30]
# Description

인증 객체를 받아내는 API 기능 구현과 StackLevelType 제거 및 모집 게시판 DTO 필드 수정
enum Type 소문자 형태로 데이터 요청 및 응답 처리 기능

# To-do
- [x] 모집 게시판 추가, 삭제 ,수정 API 구현
- [x] 모집 게시판 기술 스택 StackLevelType 제거
- [x] enum Type 소문자 형태의 요청과 응답 처리
- [x] 모집 게시판 DTO 필드 수정

# ETC
