### ISSUE TITLE
BE: User Entity 및 마이페이지 조회기능 수정

### ISSUE THREAD

**Issue by tlsrl6427** [Side-Effect-Team/side-effect-backend#31]
#Description
마이페이지 조회에서 나오는 response를 수정한다
# To-do
- [x] UserPosition 삭제
- [x] User Entity에 postion, career 추가
- [x] DTO들에서 stackLevelType 삭제
- [x] Response에서 게시글 정보도 함께 리턴

# ETC
