### ISSUE TITLE
BE: 지원 기능 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by sksrpf1126** [Side-Effect-Team/side-effect-backend#65]
# Description

지원 기능 API 수정 및 코드 리팩토링

# To-do
- [x] 지원 기능 API 수정
- [x] RecruitBoardRepository 쿼리 개선 (Querydsl)
- [x] 모집 게시판 좋아요 인덱스 도입 (Unique 제약조건)

# ETC
