### ISSUE TITLE
BE: 자랑 게시판 성능 개선과 Dto 수정

### ISSUE THREAD

**Issue by xjfcnfw3** [Side-Effect-Team/side-effect-backend#73]
#Description
자랑 게시판 성능을 개선하고 dto를 수정한다.
# To-do
- [x] 스크롤 기능 쿼리 개선
- [x] 상세 조회 필드 수정
- [x] 상세 조회 성능 개선

# ETC
