### ISSUE TITLE
BE: 모집게시판, 지원자(팀원)목록 변경

### ISSUE THREAD

**Issue by sksrpf1126** [Side-Effect-Team/side-effect-backend#78]
# Description

# To-do
- [x] 모집 게시판 scroll 조회에 모집 완료 여부 추가
- [x] 모집 게시판 상세조회에 사용자 지원 여부 추가
- [x] 지원자(팀원)목록 DTO 사용자 프로필 URL 필드 추가

# ETC
